title: Kevin Johnson
email: kevinjohnsonutx@gmail.com
domain: kevin49999.github.io
url: https://kevin49999.github.io
github_username:  kevin49999
twitter_username: kevin49999
linkedin_username: kevin499

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
