title: Kevin Johnson
email: kevinjohnsonutx@gmail.com
url: "http://johnsonkevin.com"
github_username:  kevin49999
twitter_username: kevin49999
linkedin_username: kevin499

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
