title: Kevin Johnson
email: kevinjohnsonutx@gmail.com
url: "http://johnsonkevin.com"
github_username:  longhorn499
twitter_username: dirtydan499
linkedin_username: kevin499

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
